classdef stroke
    %STROKE Building a stroke object from point generated by the arc/line
    %stroke functions. 
    
    properties
        points;
    end
    
    methods
        function obj = stroke(points)
            %STROKE Construct an instance of this class
            obj.points = points;
        end
        
        function output = getPoints(obj)
            output = [obj.points ones(length(obj.points), 1); [-1 -1 -1]];
        end
        
        function w = getWidth(obj)
            minX = min(obj.points(:,1));
            maxX = max(obj.points(:,1));
            w = maxX - minX;
        end
        
        function h = getHeight(obj)
            minY = min(obj.points(:,2));
            maxY = max(obj.points(:,2));
            h = maxY - minY;
        end
    end
end

